### ISSUE TITLE
Player name link

### ISSUE THREAD

**Issue by cyaohiri** [laytya/Prat-vanilla#2]
When a player's name is linked in a message, it shows as if the linked player sent it. Both names are clickable and the correct player can be whispered that way, but the displayed name of the sender is wrong.
When Prat is disabled, the names are displayed correctly. See the clips below.

Prat disabled:
https://user-images.githubusercontent.com/86041826/227020403-6ac546e8-2d8f-4358-8d9c-b76a6615f803.mp4

Prat enabled:
https://user-images.githubusercontent.com/86041826/227020386-e54b67f5-9eda-433e-b9ff-c0d3fa9cfd57.mp4

**Comment by laytya** [comment]
what client do you use?

**Comment by laytya** [comment]
I just cant find such functionslity in Prat - mb u using another addon for it

**Comment by cyaohiri** [comment]
Client version is 1.12.1.5875.
Prat itself does not have the functionality for linking player names, but other addons do. In this case, it was done with pfUI.
When Prat is disabled, the linked names are displayed correctly, but when Prat is enabled, the names are wrong, as demonstrated in the clips posted above.

To clarify, the person receiving the message only has the Prat addon enabled, which makes the wrong name appear. If all addons are disabled, the names are shown correctly; pfUI addon is only used on the sender's side to link a player's name in the message.
